### PR TITLE
Update Synology 1.0  to 1.1

### PR DESCRIPTION
**Pull request by ChuckPa**
Remove hard platform dependency from installation in favor of preexisting Plex Media Server installation

### CODE REVIEW

**Comment by ukdtom** [comment]
Could you please remove the binary from the src directory ?
Kinda redundancy to have it in both the src and the bin dir :-)

**Comment by ChuckPa** [comment]
Yes.   will do so.. Also am getting bit by DSM 6.   DSM 5 is ok but 6 is 
being stupid.. Please do not yet release 1.1
I will be ready later today

**Comment by ukdtom** [comment]
Ack, and awaits further info from you ;-)

**Comment by ukdtom** [comment]
Closed on req.

**Pull request closed without merging**
